### PR TITLE
Feature/sim 1370/icrs from observed

### PR DESCRIPTION
**Pull request by danielsf**
We have a lot of methods to go from the mean RA, Dec stored on fatboy to the RA, Dec actually observed by the telescope.  This pull request provides methods to do the backward transformations, so that users can take an observed pointing RA, Dec and convert them into bounds on a SQL query sent to fatboy.

You may need to work off of master in sims_utils to get the unit tests to pass (there were some bugs in the sims_utils routines that caused NaNs to come up in some cases when you asked to transform Alt, Az into RA, Dec; those have been fixed on master).

### CODE REVIEW

**Comment by danielsf** [comment]
@rhiannonlynne Do you want me to send this review to someone else?  I know you have a lot on your plate right now.

**Comment by rhiannonlynne** [comment]
Hi Scott, sorry I actually forgot about this one. I'll do it today.

**Comment by rhiannonlynne** [comment]
Looks good to me. I might have more opinions if I used these methods more  beforehand, but seems all fine. Prompted by your comments, I think it would be good if we could keep in mind what timescales we're using (and maybe standardize all of our internal timescales, like we've standardized to radians inside code, degrees external , and then provide some utilities to convert between timescales?). Maybe another ticket.

**Comment by danielsf** [comment]
I have created the JIRA issue SIM-1572 to deal with the question of time systems.

**Pull request merged**
